# Generated by Django 4.2.26 on 2026-04-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
